Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BDPlanning.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq.Dynamic.Core;
using ReflectionIT.Mvc.Paging;
using Microsoft.EntityFrameworkCore;

namespace BDPlanning.Controllers
{
    public class ReportsController : Controller
        
    {
        private readonly BDPlanningContext _context;

        public ReportsController(BDPlanningContext context)
        {
            _context = context;
        }
        // GET: Reports
        public async Task<IActionResult> ClientTrackingReports(int page = 1)
        {
            if (HttpContext.Session.GetString("usrName") != null)
            {
                
                var qry = _context.ClientTrackingInfo.AsNoTracking().OrderBy(p => p.Client.ClientActiveFlag);
                var model = await PagingList.CreateAsync(qry, 5, page);
                return View(model);
            }
            else
            {
                return RedirectToAction("Login", "Users");
            }
        }
        

        public ActionResult MeetingReports()
        {
            return View();
        }
        public void LoadDropDown()
        {
            //load client drop down, state, status and users
            List<Client> lstClient = new List<Client>();
            List<ClientTrackingStatus> lstStatus = new List<ClientTrackingStatus>();
            List<ClientTrackingState> lstState = new List<ClientTrackingState>();
            List<Users> lstUser = new List<Users>();

            Client obClient = new Client();
            obClient.ClientId = 0;
            obClient.ClientName = "--Select Client--";
            lstClient.Add(obClient);

            ClientTrackingStatus obStatus = new ClientTrackingStatus();
            obStatus.ClientTrackingStatusId = 0;
            obStatus.ClientTrackingStatusName = "--Select Tracking Status--";
            lstStatus.Add(obStatus);

            ClientTrackingState obState = new ClientTrackingState();
            obState.ClientTrackingStateId = 0;
            obState.ClientTrackingStateName = "--Select Traking State--";
            lstState.Add(obState);

            Users obUser = new Users();
            obUser.UserId = 0;
            obUser.UserName = "--Select User--";
            lstUser.Add(obUser);

            var objClient = _context.Client
                            .Where(r => r.ClientActiveFlag == true)
                            .Select(r => new { r.ClientId, r.ClientName }).ToList();

            var objStatus = _context.ClientTrackingStatus
                            .Select(r => new { r.ClientTrackingStatusId, r.ClientTrackingStatusName }).ToList();

            var objState = _context.ClientTrackingState
                           .Select(r => new { r.ClientTrackingStateId, r.ClientTrackingStateName }).ToList();

            var objUser = _context.Users
                          .Where(r => r.UserActiveFlag == true)
                          .Select(r => new { r.UserId, r.UserName }).ToList();


            foreach (var r in objClient)
            {
                Client tmpClient = new Client();
                tmpClient.ClientId = r.ClientId;
                tmpClient.ClientName = r.ClientName;
                lstClient.Add(tmpClient);
            }
            foreach (var r in objState)

            {
                ClientTrackingState tmpState = new ClientTrackingState();
                tmpState.ClientTrackingStateId = r.ClientTrackingStateId;
                tmpState.ClientTrackingStateName = r.ClientTrackingStateName;
                lstState.Add(tmpState);
            }
            foreach (var r in objStatus)
            {
                ClientTrackingStatus tmpStatus = new ClientTrackingStatus();
                tmpStatus.ClientTrackingStatusId = r.ClientTrackingStatusId;
                tmpStatus.ClientTrackingStatusName = r.ClientTrackingStatusName;
                lstStatus.Add(tmpStatus);
            }
            foreach (var r in objUser)
            {
                Users tmpUser = new Users();
                tmpUser.UserId = r.UserId;
                tmpUser.UserName = r.UserName;
                lstUser.Add(tmpUser);
            }

            ViewBag.lstClient = lstClient;
            ViewBag.lstStatus = lstStatus;
            ViewBag.lstState = lstState;
            ViewBag.lstUsers = lstUser;
        }
        [HttpPost]
        public IActionResult ClientTrackingReports(DateTime fromDate,DateTime toDate)
        {
                             var objResult = (from ct in _context.ClientTrackingInfo
                             join c in _context.Client on ct.ClientId equals c.ClientId
                             join cst in _context.ClientTrackingState on ct.TrackingStateId equals cst.ClientTrackingStateId
                             join cs in _context.ClientTrackingStatus on ct.TrackingStatusId equals cs.ClientTrackingStatusId
                             join u in _context.Users on ct.AssignedTo equals u.UserId
                             where ct.CallDate <= toDate &&ct.RemainderOn >= fromDate &&  u.UserActiveFlag == true
                             select new
                             {
                                 CallDate = ((DateTime)ct.CallDate).ToString("dd/MM/yyyy"),
                                 ClientName = c.ClientName,
                                 ClientTrackingStateName = cst.ClientTrackingStateName,
                                 ClientTrackingStatusName = cs.ClientTrackingStatusName,
                                 Comment = ct.Comment,
                                 AssignedTo = u.UserName,
                                 FollowUpDate = ct.RemainderOn
                             }).ToList();

            return View(objResult);


        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BDPlanning.Models;
using Microsoft.AspNetCore.Session;
using Microsoft.AspNetCore.Http;
using ReflectionIT.Mvc.Paging;

namespace BDPlanning.Controllers
{
    public class UsersController : Controller
    {
        private readonly BDPlanningContext _context;

        string usrName = "";

        public UsersController(BDPlanningContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index(int page=1)
        {
            if (HttpContext.Session.GetString("usrName") != null)
            {
                var qry = _context.Users.AsNoTracking().OrderBy(p => p.UserActiveFlag);
                var model = await PagingList.CreateAsync(qry, 5, page);
                return View(model);
                //return View(_context.Users.Where(r => r.UserActiveFlag == true).ToList());
            }
            else
            {
                return RedirectToAction(nameof(Login));
            }
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.Users
                .SingleOrDefaultAsync(m => m.UserId == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }

        #region CreateUsers
        // GET: Users/Create
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("usrName") != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction(nameof(Login));
            }
        }


        // POST: Users/Create
     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,UserName,UserEmail,UserMobileNumber,UserActiveFlag,CreatedBy,CreatedOn,UpdatedBy,UpdatedOn")] Users users)
        {
            if (ModelState.IsValid)
            {
                //check session
                if (HttpContext.Session.GetString("usrName") != null)
                {
                    //check if user email/mobile/name is already in the db
                    int returnFlag = 0;
                    var result = _context.Users.Where(r => r.UserEmail == users.UserEmail && r.UserActiveFlag == true).ToList();
                    if (result.Count() > 0)
                    {
                        ModelState.AddModelError("UserEmail", "Email ID already exists");

                        returnFlag++;
                    }
                    var resultMobile = _context.Users.Where(r => r.UserMobileNumber == users.UserMobileNumber && r.UserActiveFlag == true).ToList();
                    if (resultMobile.Count() > 0)
                    {
                        ModelState.AddModelError("UserMobileNumber", "Mobile number already exists");
                        returnFlag++;
                    }
                    if (returnFlag>0)
                    {
                        return View(users);
                    }

                    //created by is current session user and created on is current date
                    users.CreatedBy = HttpContext.Session.GetString("usrName");
                    users.CreatedOn = DateTime.Now;
                    //password is set to default password 
                    users.Password = "password1";
                    _context.Add(users);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction(nameof(Login));
                }
            }
            return View(users);

        }
        #endregion

        #region Login
        //GET: Users/Login
        public IActionResult Login()
        {
            return View();
        }

        //POST: Users/Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login([Bind("UserEmail,Password")] Users user)
        {
            if(ModelState.IsValid)
            {
                //change to email id
                var result = _context.Users.Where(r => r.UserEmail == user.UserEmail && r.Password == user.Password && r.UserActiveFlag == true).ToList();
                if(result.Count() > 0)
                {

                    foreach (var r in result)
                    {
                        HttpContext.Session.SetString("usrName", r.UserName);
                        HttpContext.Session.SetString("usrEmail", r.UserEmail);
                    }
                    TempData["userEmail"] = HttpContext.Session.GetString("usrEmail");
                    TempData["userName"] = HttpContext.Session.GetString("usrName");
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }
            }
            return View();
        }

        #endregion

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            //Check session
            if (HttpContext.Session.GetString("usrName") != null)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var users = await _context.Users.SingleOrDefaultAsync(m => m.UserId == id);
                if (users == null)
                {
                    return NotFound();
                }
                return View(users);
            }
            else
            {
                return RedirectToAction(nameof(Login));
            }
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,UserName,UserEmail,UserMobileNumber,UserActiveFlag,CreatedBy,CreatedOn,UpdatedBy,UpdatedOn")] Users users)
        {
            if (HttpContext.Session.GetString("usrName") != null)
            {
                if (id != users.UserId)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        //Email id and mobile number check
                        var objUser = _context.Users.SingleOrDefault(r => r.UserId == id && r.UserActiveFlag == true);
                        int returnFlag = 0;
                        var result = _context.Users.Where(r => r.UserEmail == users.UserEmail && r.UserId!=users.UserId && r.UserActiveFlag == true).ToList();
                        if (result.Count() > 0)
                        {
                            ModelState.AddModelError("UserEmail", "Email ID already exists");

                            returnFlag++;
                        }
                        var resultMobile = _context.Users.Where(r => r.UserMobileNumber == users.UserMobileNumber && r.UserId != users.UserId && r.UserActiveFlag == true).ToList();
                        if (resultMobile.Count() > 0)
                        {
                            ModelState.AddModelError("UserMobileNumber", "Mobile number already exists");
                            returnFlag++;
                        }
                        if (returnFlag > 0)
                        {
                            return View(users);
                        }

                        objUser.UserName = users.UserName;
                        objUser.UserMobileNumber = users.UserMobileNumber;
                        objUser.UserEmail = users.UserEmail;

                        objUser.UpdatedBy = HttpContext.Session.GetString("usrName");
                        objUser.UpdatedOn = DateTime.Now;
                    
                        _context.Update(objUser);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!UsersExists(users.UserId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(users);
            }
            else
            {
                return RedirectToAction(nameof(Login));
            }
        }

        // GET: Users/Delete/5
      
        public async Task<IActionResult> Delete(int? id)
        {
            if (HttpContext.Session.GetString("usrName") != null)
            {

                if (id == null)
                {
                    return NotFound();
                }
                try
                {
                    var users = await _context.Users
                        .SingleOrDefaultAsync(m => m.UserId == id);
                    if (users == null)
                    {
                        return NotFound();
                    }

                    users.UserActiveFlag = false;
                    users.UpdatedBy = HttpContext.Session.GetString("usrName");
                    users.UpdatedOn = DateTime.Now;

                    _context.Update(users);
                    await _context.SaveChangesAsync();
                }

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BDPlanning</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <style>

        /* Navbar container */
        .mynav_navbar {
            overflow: hidden;
            background-color: #333;
            font-family: Arial;
        }

        /* Links inside the navbar */
        .mynav_navbar a {
            float: left;
            font-size: 16px;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        /* The dropdown container */
        .mynav_dropdown {
            float: left;
            overflow: hidden;
        }

        /* Dropdown button */
        mynav_.dropdown .mynav_dropbtn {
            font-size: 16px;
            border: none;
            outline: none;
            color: white;
            padding: 14px 16px;
            background-color: inherit;
            font-family: inherit;
            / Important for vertical align on mobile phones / margin: 0;
            / Important for vertical align on mobile phones /
        }

        /* Add a red background color to navbar links on hover */
        .mynav_navbar a:hover, .mynav_dropdown:hover .mynav_dropbtn {
            background-color: red;
        }

        /* Dropdown content (hidden by default) */
        .mynav_dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

        /* Links inside the dropdown */
        .mynav_dropdown-content a {
            float: none;
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
            text-align: left;
        }

        /* Add a grey background color to dropdown links on hover */
        .mynav_dropdown-content a:hover {
            background-color: #ddd;
        }

        /* Show the dropdown menu on hover */
        .mynav_dropdown:hover .mynav_dropdown-content {
            display: block;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" style="width:109%; margin-left:-125px;" >
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Business Development Planning</a>
            </div>
            <div class="navbar-collapse collapse" style="padding-right:-25px; margin-right:-117px;">
                <div class="mynav_navbar" style="display:flex;">
                    <a asp-area="" asp-controller="Users" asp-action="Index">User Management</a>
                    <a asp-area="" asp-controller="Clients" asp-action="Index">Client Management</a>
                    <a asp-area="" asp-controller="ClientTracking" asp-action="CreateClientTracking">Client Tracking</a>
                    <a asp-area="" asp-controller="ClientMeetings" asp-action="Index">Meeting Management</a>
                    <div class="mynav_dropdown">
                        <a class="mynav_dropbtn">
                            Reports
                        </a>
                        <div class="mynav_dropdown-content" style="margin-top:52px">
                            <a asp-area="" asp-controller="Reports" asp-action="ClientTrackingReports">Client Tracking Reports</a>
                            <a asp-area="" asp-controller="Reports" asp-action="MeetingReports">Meeting Reports</a>
                        </div>
                    </div>



                    <a href="#"><span class="glyphicon glyphicon-bell"></span></a>
                    <a href="#"><span class="glyphicon glyphicon-user"></span>@Context.User.Identity.Name</a>
                    <a asp-area="" asp-controller="Users" asp-action="Logout"><span class="glyphicon glyphicon-log-out"></span>Logout</a>

                </div>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - BDPlanning</p>
        </footer>
    </div>

    <environment include="Development">
        @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        @*<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>*@
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BDPlanning</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>

<body>
    <h2>Business Development Planning</h2>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - BDPlanning</p>
        </footer>
    </div>

    <environment include="Development">
        @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        @*<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>*@
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>